// Package scaffold infers a starter arch.yaml from an existing tree.
package scaffold

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/yasomaru/lintel/internal/analyze"
	"github.com/yasomaru/lintel/internal/config"
	"github.com/yasomaru/lintel/internal/scan"
)

// knownLayers are directory base names that usually mark an architectural
// layer. Detection picks the shallowest matching directories.
var knownLayers = map[string]bool{
	"domain": true, "usecase": true, "usecases": true, "application": true,
	"infra": true, "infrastructure": true, "adapter": true, "adapters": true,
	"ui": true, "components": true, "hooks": true, "pages": true, "views": true,
	"api": true, "service": true, "services": true,
	"repository": true, "repositories": true,
	"controller": true, "controllers": true, "model": true, "models": true,
	"handler": true, "handlers": true, "presentation": true, "features": true,
	"core": true, "cmd": true, "internal": true, "shared": true, "utils": true,
}

type layer struct {
	Name  string
	Paths []string
}

// edge is an observed cross-layer dependency direction.
type edge struct {
	From, To string
	Count    int
}

// Generate scans root and renders a proposed arch.yaml: detected layers,
// plus the dependency directions that exist today as allow rules under
// strict mode. The generated config always passes on the tree it was
// generated from; new dependency directions then require a config change.
func Generate(root string) (string, error) {
	files, err := scan.List(root)
	if err != nil {
		return "", err
	}
	if len(files) == 0 {
		return "", fmt.Errorf("no supported source files found under %s", root)
	}
	layers := detect(files)
	return render(layers, observe(root, files, layers), len(files)), nil
}

// observe analyzes real imports and aggregates them into layer edges.
func observe(root string, files []string, layers []layer) []edge {
	tmp := &config.Config{Layers: map[string]config.Layer{}}
	for _, l := range layers {
		tmp.Layers[l.Name] = config.Layer{Path: l.Paths}
	}
	layerOf := make(map[string]string, len(files))
	for _, f := range files {
		layerOf[f] = scan.LayerOf(f, tmp)
	}
	results := analyze.NewProject(root, files, analyze.Options{}).All(files)
	counts := map[[2]string]int{}
	for f, res := range results {
		from := layerOf[f]
		if from == "" {
			continue
		}
		for _, imp := range res.Imports {
			to := layerOf[imp.Resolved]
			if imp.Resolved != "" && to != "" && to != from {
				counts[[2]string{from, to}]++
			}
		}
	}
	out := make([]edge, 0, len(counts))
	for k, n := range counts {
		out = append(out, edge{From: k[0], To: k[1], Count: n})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].From != out[j].From {
			return out[i].From < out[j].From
		}
		return out[i].To < out[j].To
	})
	return out
}

// detect returns proposed layers, grouped by directory base name.
func detect(files []string) []layer {
	// Every ancestor directory of every source file, with file counts.
	counts := map[string]int{}
	for _, f := range files {
		for d := path.Dir(f); d != "." && d != "/"; d = path.Dir(d) {
			counts[d]++
		}
	}
	dirs := make([]string, 0, len(counts))
	for d := range counts {
		dirs = append(dirs, d)
	}
	// Shallowest first so nested known dirs defer to their ancestors.
	sort.Slice(dirs, func(i, j int) bool {
		di, dj := strings.Count(dirs[i], "/"), strings.Count(dirs[j], "/")
		if di != dj {
			return di < dj
		}
		return dirs[i] < dirs[j]
	})
	var cands []string
	for _, d := range dirs {
		if !knownLayers[path.Base(d)] || hasAncestor(cands, d) {
			continue
		}
		cands = append(cands, d)
	}
	if len(cands) == 0 {
		// Fallback: top-level directories holding source files.
		top := map[string]bool{}
		for _, f := range files {
			if i := strings.Index(f, "/"); i > 0 {
				top[f[:i]] = true
			}
		}
		for d := range top {
			cands = append(cands, d)
		}
		sort.Strings(cands)
	}
	grouped := map[string][]string{}
	for _, d := range cands {
		name := path.Base(d)
		grouped[name] = append(grouped[name], d+"/**")
	}
	names := make([]string, 0, len(grouped))
	for n := range grouped {
		names = append(names, n)
	}
	sort.Strings(names)
	out := make([]layer, len(names))
	for i, n := range names {
		sort.Strings(grouped[n])
		out[i] = layer{Name: n, Paths: grouped[n]}
	}
	return out
}

func hasAncestor(cands []string, d string) bool {
	for _, c := range cands {
		if strings.HasPrefix(d, c+"/") {
			return true
		}
	}
	return false
}

func render(layers []layer, edges []edge, fileCount int) string {
	var b strings.Builder
	b.WriteString("# yaml-language-server: $schema=https://raw.githubusercontent.com/yasomaru/lintel/main/docs/arch.schema.json\n")
	fmt.Fprintf(&b, "# Generated by `lintel init --scan` from %d source file(s).\n", fileCount)
	b.WriteString("# The allow rules below record every cross-layer dependency observed in\n")
	b.WriteString("# the scan, so this config passes today. With strict mode on, any NEW\n")
	b.WriteString("# dependency direction fails the check until it is added here.\n\n")

	b.WriteString("layers:\n")
	for _, l := range layers {
		fmt.Fprintf(&b, "  %s:\n", l.Name)
		if len(l.Paths) == 1 {
			fmt.Fprintf(&b, "    path: %q\n", l.Paths[0])
		} else {
			fmt.Fprintf(&b, "    path: [%s]\n", quoteJoin(l.Paths))
		}
		b.WriteString("    description: TODO describe this layer's responsibility\n")
	}

	b.WriteString("\nstrict: true\n\nrules:\n")
	outgoing := map[string]bool{}
	for _, e := range edges {
		outgoing[e.From] = true
	}
	wrote := false
	for _, e := range edges {
		fmt.Fprintf(&b, "  - allow: %s -> %s   # %d import(s) today\n", e.From, e.To, e.Count)
		wrote = true
	}
	// A layer named "domain" with no outward dependencies is worth locking
	// down explicitly; if it has some, only suggest the lockdown.
	hasDomain := false
	for _, l := range layers {
		if l.Name == "domain" {
			hasDomain = true
		}
	}
	if hasDomain && !outgoing["domain"] {
		b.WriteString("  - deny: domain -> \"*\"\n")
		b.WriteString("    reason: The domain layer depends on nothing today. Keep it that way.\n")
		wrote = true
	} else if hasDomain {
		b.WriteString("  # Your domain layer currently depends on other layers. Once that\n")
		b.WriteString("  # debt is paid down, lock it in:\n")
		b.WriteString("  # - deny: domain -> \"*\"\n")
	}
	if !wrote {
		b.WriteString("  # No cross-layer dependencies observed. New ones will need an\n")
		b.WriteString("  # allow rule here (strict mode).\n")
		b.WriteString("  []\n")
	}

	b.WriteString(`
# Uncomment what you want to enforce. Docs: https://github.com/yasomaru/lintel
#
# coverage:
#   require-layer: true
#   reason: Every file belongs to a declared layer.
#
# suppressions:
#   deny: ["@ts-ignore", "eslint-disable"]
#   reason: Fix the root cause instead of suppressing.
#
# metrics:
#   - target: "src/**"
#     max-lines: 300
#     max-imports: 15
#
# baseline: .lintel-baseline.json
`)
	return b.String()
}

func quoteJoin(ss []string) string {
	q := make([]string, len(ss))
	for i, s := range ss {
		q[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(q, ", ")
}
