// Package scaffold infers a starter arch.yaml from an existing tree.
package scaffold

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/yasomaru/lintel/internal/scan"
)

// knownLayers are directory base names that usually mark an architectural
// layer. Detection picks the shallowest matching directories.
var knownLayers = map[string]bool{
	"domain": true, "usecase": true, "usecases": true, "application": true,
	"infra": true, "infrastructure": true, "adapter": true, "adapters": true,
	"ui": true, "components": true, "hooks": true, "pages": true, "views": true,
	"api": true, "service": true, "services": true,
	"repository": true, "repositories": true,
	"controller": true, "controllers": true, "model": true, "models": true,
	"handler": true, "handlers": true, "presentation": true, "features": true,
	"core": true, "cmd": true, "internal": true, "shared": true, "utils": true,
}

type layer struct {
	Name  string
	Paths []string
}

// Generate scans root and renders a proposed arch.yaml.
func Generate(root string) (string, error) {
	files, err := scan.List(root)
	if err != nil {
		return "", err
	}
	if len(files) == 0 {
		return "", fmt.Errorf("no supported source files found under %s", root)
	}
	return render(detect(files), len(files)), nil
}

// detect returns proposed layers, grouped by directory base name.
func detect(files []string) []layer {
	// Every ancestor directory of every source file, with file counts.
	counts := map[string]int{}
	for _, f := range files {
		for d := path.Dir(f); d != "." && d != "/"; d = path.Dir(d) {
			counts[d]++
		}
	}
	dirs := make([]string, 0, len(counts))
	for d := range counts {
		dirs = append(dirs, d)
	}
	// Shallowest first so nested known dirs defer to their ancestors.
	sort.Slice(dirs, func(i, j int) bool {
		di, dj := strings.Count(dirs[i], "/"), strings.Count(dirs[j], "/")
		if di != dj {
			return di < dj
		}
		return dirs[i] < dirs[j]
	})
	var cands []string
	for _, d := range dirs {
		if !knownLayers[path.Base(d)] || hasAncestor(cands, d) {
			continue
		}
		cands = append(cands, d)
	}
	if len(cands) == 0 {
		// Fallback: top-level directories holding source files.
		top := map[string]bool{}
		for _, f := range files {
			if i := strings.Index(f, "/"); i > 0 {
				top[f[:i]] = true
			}
		}
		for d := range top {
			cands = append(cands, d)
		}
		sort.Strings(cands)
	}
	grouped := map[string][]string{}
	for _, d := range cands {
		name := path.Base(d)
		grouped[name] = append(grouped[name], d+"/**")
	}
	names := make([]string, 0, len(grouped))
	for n := range grouped {
		names = append(names, n)
	}
	sort.Strings(names)
	out := make([]layer, len(names))
	for i, n := range names {
		sort.Strings(grouped[n])
		out[i] = layer{Name: n, Paths: grouped[n]}
	}
	return out
}

func hasAncestor(cands []string, d string) bool {
	for _, c := range cands {
		if strings.HasPrefix(d, c+"/") {
			return true
		}
	}
	return false
}

func render(layers []layer, fileCount int) string {
	var b strings.Builder
	b.WriteString("# yaml-language-server: $schema=https://raw.githubusercontent.com/yasomaru/lintel/main/docs/arch.schema.json\n")
	fmt.Fprintf(&b, "# Generated by `lintel init --scan` from %d source file(s).\n", fileCount)
	b.WriteString("# Review the layers, then uncomment and adapt the rules below.\n\n")

	b.WriteString("layers:\n")
	for _, l := range layers {
		fmt.Fprintf(&b, "  %s:\n", l.Name)
		if len(l.Paths) == 1 {
			fmt.Fprintf(&b, "    path: %q\n", l.Paths[0])
		} else {
			fmt.Fprintf(&b, "    path: [%s]\n", quoteJoin(l.Paths))
		}
		b.WriteString("    description: TODO describe this layer's responsibility\n")
	}

	has := map[string]bool{}
	for _, l := range layers {
		has[l.Name] = true
	}
	b.WriteString("\nrules:\n")
	wrote := false
	if has["domain"] {
		b.WriteString("  - deny: domain -> \"*\"\n")
		b.WriteString("    reason: The domain layer must not depend on any other layer.\n")
		wrote = true
		for _, dep := range []string{"infra", "infrastructure", "usecase", "usecases", "api"} {
			if has[dep] {
				fmt.Fprintf(&b, "  - allow: %s -> domain\n", dep)
			}
		}
	}
	if !wrote {
		if len(layers) >= 2 {
			fmt.Fprintf(&b, "  # - allow: %s -> %s\n", layers[0].Name, layers[1].Name)
			fmt.Fprintf(&b, "  # - deny: %s -> %s\n", layers[1].Name, layers[0].Name)
		}
		b.WriteString("  #   reason: explain why, both for humans and AI agents\n")
		b.WriteString("  []\n")
	}

	b.WriteString(`
# Uncomment what you want to enforce. Docs: https://github.com/yasomaru/lintel
#
# coverage:
#   require-layer: true
#   reason: Every file belongs to a declared layer.
#
# suppressions:
#   deny: ["@ts-ignore", "eslint-disable"]
#   reason: Fix the root cause instead of suppressing.
#
# metrics:
#   - target: "src/**"
#     max-lines: 300
#     max-imports: 15
#
# baseline: .lintel-baseline.json
`)
	return b.String()
}

func quoteJoin(ss []string) string {
	q := make([]string, len(ss))
	for i, s := range ss {
		q[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(q, ", ")
}
